### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by karldanninger** [ManuelDeLeon/meteor-ssr#1]
Yo, this repo was exactly what I was looking for, but it doesn't even run. Very sad day :'(

```
E20180805-19:37:12.037(-4) (webapp_server.js:900) Error running template: TypeError: Cannot read property 'match' of undefined
    at getCookies (server/cookies.js:6:14)
    at sink (server/ssr.js:20:19)
    at onPageLoad.chain.callback (packages/server-render/server-register.js:14:19)
    at promise.then (packages/server-render/server.js:28:36)
    at /Users/karldanninger/.meteor/packages/promise/.0.11.1.1ikmzfk.pchl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

on fresh clone. Any ideas? Something to do with your cookie code...

**Comment by ManuelDeLeon** [comment]
Better late than never... I recently updated the boilerplate up to the latest meteor.
